### ISSUE TITLE
New message on RPCh start: `Please update your RPCh Docker Image`

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#537] opened 2023-10-12 08:22 UTC
### Is your feature related to a problem?

Users might not know if they need to update their Docker Image

### Describe the feature you'd like

New message on RPCh start: `Please update your RPCh Docker Image` based off the config DB table and the RPCh_DOCKER_IMAGE_VERSION key.
Linked FE issue: https://github.com/Rpc-h/degen-rpch-net/issues/52

### Possible sollution

Possible Docker cmd to know the verison inside PROD image: 

```
RUN apt-get update && \
    apt-get install jq

RUN jq .version package.json -r > /app/version.txt
```

**Comment by esterlus** [comment] 2023-10-27 13:01
Closed as duplicate of https://github.com/Rpc-h/RPCh/issues/559

**Closed by esterlus** 2023-10-27 13:01 UTC
Labels: enhancement
